# ============================================================================
# TERRAFORM BACKEND CONFIGURATION - AZURE REMOTE STATE
# ============================================================================
# This file was auto-generated by preprovision.sh.
# Backend values are provided via -backend-config=provider.conf.json during init.
#
# To switch to local state for development:
#   azd env set LOCAL_STATE "true"
#   azd hooks run preprovision

terraform {
  backend "azurerm" {
    use_azuread_auth = true
  }
}
